<?php

/**
 * WeEngine Api System
 *
 * (c) We7Team 2019 <https://www.w7.cc>
 *
 * This is not a free software
 * Using it under the license terms
 * visited https://www.w7.cc for more details
 */

namespace W7\Sdk\OpenCloud\Util;

use PhpZip\Model\EndOfCentralDirectory;
use PhpZip\Model\ZipEntry;

class ZipReader extends \PhpZip\IO\ZipReader {
	public function readEndOfCentralDirectory() {
		return parent::readEndOfCentralDirectory();
	}

	public function readCentralDirectory(EndOfCentralDirectory $endCD) {
		return parent::readCentralDirectory($endCD); // TODO: Change the autogenerated stub
	}

	protected function loadLocalExtraFields(ZipEntry $entry) {
		//不获取实际文件内容
	}
}
