<?php

/**
 * WeEngine Cloud SDK System
 *
 * (c) We7Team 2019 <https://www.w7.cc>
 *
 * This is not a free software
 * Using it under the license terms
 * visited https://www.w7.cc for more details
 */

namespace W7\Sdk\Cloud\Tests;

use W7\Sdk\Cloud\Cache\File;

trait Helper {
	private $rootPath = '/Users/renchao/Workspace/php/we7/donknap.we7.cc';
	private $fileCacher;

	public static $random;

	public static function setUpBeforeClass(): void {
		$rootPath = '/Users/renchao/Workspace/php/we7/donknap.we7.cc';

		!defined('IN_IA') && define('IN_IA', true);
		!defined('IA_ROOT') && define('IA_ROOT', $rootPath);

		require_once $rootPath . '/data/config.php';
		require_once $rootPath . '/framework/class/loader.class.php';

		load()->func('global');
		load()->func('pdo');

		$config['db']['master']['host'] = '127.0.0.1';
		$GLOBALS['_W']['config'] = $config;
		$GLOBALS['_W']['config']['db']['tablepre'] = !empty($GLOBALS['_W']['config']['db']['master']['tablepre']) ? $GLOBALS['_W']['config']['db']['master']['tablepre'] : $GLOBALS['_W']['config']['db']['tablepre'];

		$row = pdo_get('core_cache', [
			'key' => 'we7:random',
		]);

		self::$random = unserialize($row['value'])['data'];
		echo self::$random, PHP_EOL;
		!defined('W7_CLOUD_SDK_AUTHKEY') && define('W7_CLOUD_SDK_AUTHKEY', $GLOBALS['_W']['config']['setting']['authkey']);

		parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
	}

	public function __construct($name = null, array $data = [], $dataName = '') {
		$this->fileCacher = new File($this->rootPath . '/data');
		parent::__construct($name, $data, $dataName);
	}

	/**
	 * @return \W7\Sdk\Cloud\Message\SiteInfo
	 */
	public function getSiteInfo() {
		$data = [
			'host' => 'donknap.w7.cc',
			'family' => 'v',
			'php_version' => '2.5.7',
			'current_host' => 'donknap.w7.cc',
			'release' => '201910150001',
			'key' => '220206',
			'password' => '7474b9597d69705992c1bd2d064b6dc0',
			'client' => '364dfceffb13abcbbfd5cc53b5113496',
			'method' => 'module.query',
			'encode' => 'base64',
		];

		$siteinfo = new \W7\Sdk\Cloud\Message\SiteInfo();
		$siteinfo->setKey($data['key']);
		$siteinfo->setFamily($data['family']);
		$siteinfo->setHost($data['host']);
		$siteinfo->setRelease($data['release']);
		$siteinfo->setToken('3d1ce8d5eecdf34275861dd9fea5fa3f');
		$siteinfo->setVersion('1.2.3');

		return $siteinfo;
	}

	/**
	 * @return \W7\Sdk\Cloud\Message\SiteInfo
	 */
	public function getCCCeShiSiteInfo() {
		$data = [
			'host' => 'ccceshi.w7.cc',
			'family' => 'v',
			'php_version' => '2.5.7',
			'current_host' => 'ccceshi.w7.cc',
			'release' => '201910150001',
			'key' => '112982',
			'password' => 'ab7f9463df4854dadb7e3094e3245f26',
			'client' => '364dfceffb13abcbbfd5cc53b5113496',
			'method' => 'module.query',
			'encode' => 'base64',
		];

		$siteinfo = new \W7\Sdk\Cloud\Message\SiteInfo();
		$siteinfo->setKey($data['key']);
		$siteinfo->setFamily($data['family']);
		$siteinfo->setHost($data['host']);
		$siteinfo->setRelease($data['release']);
		$siteinfo->setToken('d659404b91c7e556a5e0a528764346fe');
		$siteinfo->setVersion('1.2.3');

		return $siteinfo;
	}
}
